eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

server:
  port: 8084
spring:
  application:
    name: sip-ribbon

  boot:
    admin:
      client:
        url: 'http://localhost:1700' # 基于 Spring Boot 项目的监控地址

  zipkin: #服务链路追踪
    base-url: http://localhost:9411

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"



